// <auto-generated />
using System;
using BlazorProperty.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorProperty.Migrations
{
    [DbContext(typeof(BlazorPropertyContext))]
    [Migration("20250208141522_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorProperty.Domain.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            CompanyDescription = "XYZ real estate provides the newest and greatest properties",
                            CompanyName = "XYZ realestate"
                        },
                        new
                        {
                            CompanyId = 2,
                            CompanyDescription = "ABC Real Estate was founded in 1982",
                            CompanyName = "ABC Real Estate"
                        });
                });

            modelBuilder.Entity("BlazorProperty.Domain.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityId"));

                    b.Property<string>("FacilityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("FacilityId");

                    b.HasIndex("RegionId");

                    b.ToTable("Facility");

                    b.HasData(
                        new
                        {
                            FacilityId = 1,
                            FacilityDescription = "Food centre for singaporean",
                            FacilityName = "Hawker",
                            RegionId = 1
                        },
                        new
                        {
                            FacilityId = 2,
                            FacilityName = "Gym",
                            RegionId = 1
                        });
                });

            modelBuilder.Entity("BlazorProperty.Domain.Inquiry", b =>
                {
                    b.Property<int>("InquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InquiryId"));

                    b.Property<DateTime>("DateOfInquiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InquiryId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Inquiry");
                });

            modelBuilder.Entity("BlazorProperty.Domain.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.HasKey("PropertyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Property");

                    b.HasData(
                        new
                        {
                            PropertyId = 1,
                            Address = "Tampines Blk 123",
                            Bathrooms = 3,
                            Bedrooms = 5,
                            PostalCode = "330022",
                            Price = 1000000,
                            PropertyType = "HDB",
                            RegionId = 1,
                            Sqft = 1100
                        },
                        new
                        {
                            PropertyId = 2,
                            Address = "Bedok Blk 456",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            PostalCode = "123456",
                            Price = 400000,
                            PropertyType = "HDB",
                            RegionId = 1,
                            Sqft = 700
                        },
                        new
                        {
                            PropertyId = 3,
                            Address = "Kallang Blk 123",
                            Bathrooms = 2,
                            Bedrooms = 4,
                            PostalCode = "364029",
                            Price = 750000,
                            PropertyType = "HDB",
                            RegionId = 2,
                            Sqft = 890
                        },
                        new
                        {
                            PropertyId = 4,
                            Address = "Jurong East Blk456",
                            Bathrooms = 2,
                            Bedrooms = 4,
                            PostalCode = "326432",
                            Price = 888888,
                            PropertyType = "HDB",
                            RegionId = 4,
                            Sqft = 888
                        });
                });

            modelBuilder.Entity("BlazorProperty.Domain.PropertyImage", b =>
                {
                    b.Property<int>("PropertyImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("PropertyImageId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImage");
                });

            modelBuilder.Entity("BlazorProperty.Domain.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("RegionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Region");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            RegionDescription = "Located on the east side of singapore like Tampines",
                            RegionName = "East"
                        },
                        new
                        {
                            RegionId = 2,
                            RegionDescription = "The Singapore Central Region with towns like Kallang",
                            RegionName = "Central"
                        },
                        new
                        {
                            RegionId = 3,
                            RegionDescription = "Woodlands",
                            RegionName = "North"
                        },
                        new
                        {
                            RegionId = 4,
                            RegionDescription = "Jurong",
                            RegionName = "West"
                        },
                        new
                        {
                            RegionId = 5,
                            RegionDescription = "Punggol area",
                            RegionName = "North east"
                        });
                });

            modelBuilder.Entity("BlazorProperty.Domain.Facility", b =>
                {
                    b.HasOne("BlazorProperty.Domain.Region", "Region")
                        .WithMany("Facilities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("BlazorProperty.Domain.Inquiry", b =>
                {
                    b.HasOne("BlazorProperty.Domain.Property", "Property")
                        .WithMany("PropertiesInquiries")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("BlazorProperty.Domain.Property", b =>
                {
                    b.HasOne("BlazorProperty.Domain.Region", "Region")
                        .WithMany("Properties")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("BlazorProperty.Domain.PropertyImage", b =>
                {
                    b.HasOne("BlazorProperty.Domain.Property", "Property")
                        .WithMany("PropertyImages")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("BlazorProperty.Domain.Property", b =>
                {
                    b.Navigation("PropertiesInquiries");

                    b.Navigation("PropertyImages");
                });

            modelBuilder.Entity("BlazorProperty.Domain.Region", b =>
                {
                    b.Navigation("Facilities");

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
